// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: app/grpc-server/controller/proto/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryStatus int32

const (
	InventoryStatus_INVENTORY_STATUS_UNSPECIFIED InventoryStatus = 0
	InventoryStatus_ACTIVE                       InventoryStatus = 1
	InventoryStatus_BROKEN                       InventoryStatus = 2
)

// Enum value maps for InventoryStatus.
var (
	InventoryStatus_name = map[int32]string{
		0: "INVENTORY_STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "BROKEN",
	}
	InventoryStatus_value = map[string]int32{
		"INVENTORY_STATUS_UNSPECIFIED": 0,
		"ACTIVE":                       1,
		"BROKEN":                       2,
	}
)

func (x InventoryStatus) Enum() *InventoryStatus {
	p := new(InventoryStatus)
	*p = x
	return p
}

func (x InventoryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_app_grpc_server_controller_proto_inventory_proto_enumTypes[0].Descriptor()
}

func (InventoryStatus) Type() protoreflect.EnumType {
	return &file_app_grpc_server_controller_proto_inventory_proto_enumTypes[0]
}

func (x InventoryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryStatus.Descriptor instead.
func (InventoryStatus) EnumDescriptor() ([]byte, []int) {
	return file_app_grpc_server_controller_proto_inventory_proto_rawDescGZIP(), []int{0}
}

type InventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        InventoryStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=inventory.InventoryStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryRequest) Reset() {
	*x = InventoryRequest{}
	mi := &file_app_grpc_server_controller_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryRequest) ProtoMessage() {}

func (x *InventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_server_controller_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryRequest.ProtoReflect.Descriptor instead.
func (*InventoryRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_server_controller_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InventoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *InventoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InventoryRequest) GetStatus() InventoryStatus {
	if x != nil {
		return x.Status
	}
	return InventoryStatus_INVENTORY_STATUS_UNSPECIFIED
}

var File_app_grpc_server_controller_proto_inventory_proto protoreflect.FileDescriptor

const file_app_grpc_server_controller_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"0app/grpc-server/controller/proto/inventory.proto\x12\tinventory\"\xa6\x01\n" +
	"\x10InventoryRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.inventory.InventoryStatusR\x06status*K\n" +
	"\x0fInventoryStatus\x12 \n" +
	"\x1cINVENTORY_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\n" +
	"\n" +
	"\x06BROKEN\x10\x02B\rZ\v./inventoryb\x06proto3"

var (
	file_app_grpc_server_controller_proto_inventory_proto_rawDescOnce sync.Once
	file_app_grpc_server_controller_proto_inventory_proto_rawDescData []byte
)

func file_app_grpc_server_controller_proto_inventory_proto_rawDescGZIP() []byte {
	file_app_grpc_server_controller_proto_inventory_proto_rawDescOnce.Do(func() {
		file_app_grpc_server_controller_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_grpc_server_controller_proto_inventory_proto_rawDesc), len(file_app_grpc_server_controller_proto_inventory_proto_rawDesc)))
	})
	return file_app_grpc_server_controller_proto_inventory_proto_rawDescData
}

var file_app_grpc_server_controller_proto_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_grpc_server_controller_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_grpc_server_controller_proto_inventory_proto_goTypes = []any{
	(InventoryStatus)(0),     // 0: inventory.InventoryStatus
	(*InventoryRequest)(nil), // 1: inventory.InventoryRequest
}
var file_app_grpc_server_controller_proto_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryRequest.status:type_name -> inventory.InventoryStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_grpc_server_controller_proto_inventory_proto_init() }
func file_app_grpc_server_controller_proto_inventory_proto_init() {
	if File_app_grpc_server_controller_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_grpc_server_controller_proto_inventory_proto_rawDesc), len(file_app_grpc_server_controller_proto_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_grpc_server_controller_proto_inventory_proto_goTypes,
		DependencyIndexes: file_app_grpc_server_controller_proto_inventory_proto_depIdxs,
		EnumInfos:         file_app_grpc_server_controller_proto_inventory_proto_enumTypes,
		MessageInfos:      file_app_grpc_server_controller_proto_inventory_proto_msgTypes,
	}.Build()
	File_app_grpc_server_controller_proto_inventory_proto = out.File
	file_app_grpc_server_controller_proto_inventory_proto_goTypes = nil
	file_app_grpc_server_controller_proto_inventory_proto_depIdxs = nil
}
